/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wtGXJ3AUXAq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client"

import Image from "next/image"
import { Button } from "@/components/ui/button"
import { useCartStore } from "@/stores/cart/cartStore"
import { useToast } from "@/components/ui/use-toast"

export interface Product {
  id: string,
  name: string, 
  price: number,
  description: string,
  imageURL: string
}

export function Product({product}: {product: Product}) {
  const updateCart = useCartStore((state) => state.updateCart);
  const { toast } = useToast();

  const updateCartHandler = (product: Product) => {
    // updated the cart with one item
    updateCart(product, 1)

    toast({
      title: "Item added to cart",
      description: `You've added: ${product.name} to you cart.`,
    });
  }

  return (
    <section className="w-full py-12">
      <div className="container grid gap-6 md:gap-8 px-4 md:px-6">
        <div className="grid gap-4">
          <div className="grid gap-2.5 relative group">
            <Image
              src={product.imageURL}
              alt={product.description}
              width={300}
              height={300}
              className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
            />
            <div className="grid gap-1">
              <h3 className="font-semibold">{product.name}</h3>
              <p className="text-sm leading-none text-muted-foreground">{product.description}</p>
              <div className="flex items-center justify-between">
                <h4 className="font-semibold">$ {product.price}</h4>
                <Button 
                  variant="outline" 
                  className="px-4 py-2"
                  onClick={() => updateCartHandler(product)}
                >
                  Add to Cart
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
